name: "Install python dependencies"
inputs:
  uv-sync-args:
    required: false
    default: "--dev --no-sources"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the project
      run: uv sync ${{ inputs.uv-sync-args }}
      shell: bash