name: "Install python dependencies for playwright"

runs:
  using: "composite"
  steps:
    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ matrix.python-version }}-1.57.0
        restore-keys: |
          playwright-${{ runner.os }}-${{ matrix.python-version }}-1.57.0-

    # Prevent "man-db" trigger updates during apt installs, which can take a long time
    - name: Remove man-db
      run: sudo apt-get purge -y man-db
      shell: bash

    - name: Create uv virtual environment
      run: uv python pin ${{ matrix.python-version }}
      shell: bash

    - name: Project deps
      run: uv sync --group web --group playwright --group test --no-sources
      shell: bash

    - name: Install Playwright
      run: |
        # Install playwright dependencies if not cached
        if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
          uv run playwright install chromium --with-deps
        fi
      shell: bash