name: "Main Branch Playwright Cache"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  main-playwright-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ inputs.python-version }}-1.48.0-${{ github.run_id }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create uv virtual environment
        run: |
          uv init
          uv python pin ${{ inputs.python-version }}
        shell: bash

      - name: Install Playwright & project deps
        run: |
          uv add playwright==1.48.0

          # Install playwright dependencies if not cached
          if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
            uv run playwright install chromium --with-deps
          fi
        shell: bash

      - name: Log cache status
        run: |
          if [ "${{ steps.playwright-cache.outputs.cache-hit }}" == "true" ]; then
            echo "✅ Cache HIT"
          else
            echo "❌ Cache MISS"
          fi